### ISSUE TITLE
Check bad temperature probes cannot be selected

### ISSUE THREAD

**Issue by jwaterfield** [snoplus/tellie#4]
Test with boards and fix if the bad temperature probes are being selected. 

Bad temperature probes should be noted in the code somehow to ensure they are not used again. Use  the next nearest probe. 

There is one bad temperature probe in TELLIE. Unknown location currently. Can also test with disconnected AMELLIE probes.

**Comment by mnirkko** [comment]
We are not using temperature probes UG (or on test bench), suggest closing.
