### ISSUE TITLE
Admin rights on this repo

### ISSUE THREAD

**Issue by mnirkko** [snoplus/tellie#49]
It seems like we have no more active admins on this repo - could @mastbaum or @EdLeming please add the current TELLIE experts as admins? That would be Martti and Michal...

**Comment by MRiganSUSX** [comment]
@mnirkko @MRiganSUSX

**Comment by EdLeming** [comment]
The tellie-admin team is defined globally as part of the snoplus organisation (link below). As far as I can tell I don't have rights to update it. I think you need @mastbaum to action this. 

https://github.com/orgs/snoplus/teams/tellie-admin

**Comment by mnirkko** [comment]
Ah, Andy says:

> The bus factor isn't quite so bad! There are a few people who should have admin-level rights to the whole SNO+ organization, and be able to do anything needed as far as permissions management. Currently this also includes: Gabriel, Jeanne, Jeff Tseng, Juan Pablo, Nuno, Rebecca Lane, and John Roberts. (To see owners, go to People on github.com/snoplus and filter by Role).

@tsengj10 @nbarros @drjeannewilson perhaps one of you can sort this out? :)

**Comment by mnirkko** [comment]
Done - @mnirkko and @MRiganSUSX now are members of the tellie-admin team.
https://github.com/orgs/snoplus/teams/tellie-admin
