### ISSUE TITLE
Develop Default Run Setting

### ISSUE THREAD

**Issue by jwaterfield** [snoplus/tellie#8]
Store in database. Vague structure to be devloped so far is:

Pattern Documenent:
sub run #: fibre map->(ID,Wavelength, Time Profile ..)

Run Document:
Pattern # 
Sub Run #: 
                PIN readings
                Settings: IOP, IPW, Rate, Number of pulses

Event Data Structure (NOT IN DB)
Pattern # 
Subrun #

**Comment by mnirkko** [comment]
I think this has been implemented on CouchDB. Suggest closing.
